# Conclusions and recommendations

> "Knowledge is knowing that a tomato is a fruit; wisdom is not putting it in a fruit salad."

> `r quote_footer('--- Miles Kington')`

Studying and thinking with graphics is different.  It is about staying flexible, being open to new ideas, drawing many graphics---varying, amending, and adjusting them.  Text is read in a given order, a graphic may be viewed in any order.  Sometimes the information in a graphic is obvious, sometimes it takes more time and effort to see what is there.  The graphic has to be "grounded", based on a firm foundation of background knowledge.  You need time to think and space to view.

This book has concentrated on exploratory graphics rather than presentation graphics.  The difference is not a simple dichotomy.  There are raw exploratory graphics, drawn quickly for content and relying on good defaults.  There are amended exploratory graphics with adjustments and improvements to emphasise features.   Finally there are polished presentation graphics to attract attention and to impress.  Some of the graphics in the examples have been adjusted and amended more than others, often because studying graphics stimulates you to modify them and improving them supports your thinking about the graphics.  Some exploratory graphics can be much improved with a few adjustments and amendments.  Some default graphics can look fairly bad unless something is done about them.

Where there is a difference between exploratory and presentation graphics is in the workflow.  Exploratory graphics are studied to discover information, to look for content, and there may be many different graphics.  To get the most value from them, you have to have expectations of what you might see.  Presentation graphics are drawn to present information, to improve their look, and, while there may be many drafts of related ones, at most a few are shown.  To draw an effective presentation graphic, you have to have a picture of what you want others to see.  

There are no piecharts, waffle charts, pictograms or examples of the many other chart types there are in this book.  This is no reflection on them.  Everyone can use the charts they find most informative.  The general advice on layout, colour, ordering, formatting, and so on applies just as well to these chart types as to those in the book.  Varying graphics, using many of them, and checking insights is good practice whichever graphic forms are used.

Several interesting and important topics for graphics deserve more attention.  Some like perception, design, and displaying uncertainty are more relevant for presentation graphics.  Some like graphics for spatial data are more specialist.  Interactive graphics\index{interactive graphics} really deserves a book of its own---once there is suitable software that is sufficiently fast, flexible, effective, and integrated with other systems.

The datasets in the book have been chosen because they were interesting and because they were available.  There was no attempt to pick datasets to illustrate or show off particular graphical tools.  Graphics reveal more information in some datasets than in others.  For every statistical method of whatever kind, whether a graphic or a model, there is doubtless an Achilles heel dataset that it just cannot cope with.  Suggestions of such datasets would be welcome.

Some claim that 10000 hours of deliberate practice is enough to turn a person into an expert.  The key word is the undefined 'deliberate'.  Reading the case studies, evaluating the graphics, and trying out alternatives might well be a good step in the right direction.  Check the results produced using your own graphics.  Look for other results by questioning the book's datasets and by studying datasets of your own.
