library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.align = "center")
library(tidyverse)
theme_set(theme(plot.title = element_text(hjust = 0.5)))
library(ggthemes)
library(patchwork)
library(lubridate)
library(tufte)
library(ggmosaic)
library(readxl)
library(sf)
library(tmap)
library(tmaptools)
library(GmooG)
